import { useEffect, useMemo, useRef, useState } from "react";
import type { MouseEvent } from "react";
import {
  AlertTriangle,
  Anchor,
  Box,
  Calendar,
  Clock,
  Globe,
  Grid,
  Image,
  LayoutDashboard,
  Map,
  Maximize,
  PieChart,
  Ship,
  Tag,
} from "lucide-react";
import { SearchField } from "../components/SearchField";
import { Sidebar, SidebarBody, SidebarHeader } from "../components/Sidebar";
import { SectionTitle } from "../components/SectionTitle";
import { StatCard, StatRow } from "../components/StatCard";
import { ButtonGrid, ToggleButton } from "../components/ToggleButton";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
declare module "plotly.js-dist-min";

import rawDashboardData from "../data/port_dashboard.json";
import type { DashboardPort, PortDashboardData, ProfileResult } from "../lib/types";
import { useTooltip } from "../lib/useTooltip";
import { UI_FONT } from "../lib/theme";
import { PlotsGrid } from "./PlotsGrid";
import { ClusterMetrics } from "./ClusterMetrics";
import { PortComparePanel } from "./PortComparePanel";
import { compareHoverText, comparePort, featureLabel, profileMeans, shortGroupName } from "./hover";

// Generated by source/analysis/ports/generate_dashboard.py (strict JSON,
// non-finite floats sanitized at write time).
const data = rawDashboardData as PortDashboardData;
const CLUSTER_PALETTE = [
  "#3b82f6",
  "#10b981",
  "#f59e0b",
  "#8b5cf6",
  "#ef4444",
  "#06b6d4",
  "#ec4899",
  "#14b8a6",
];

const PLOTS_BASE_PATH = "ports/output/plots/";

type ViewMode = "2d" | "3d" | "map" | "corr" | "plots";
type ColorMode = "dominant" | "cluster";

const PROFILE_ICONS: Record<string, typeof Ship> = {
  fleet_mix: Ship,
  operations: Clock,
  scale: Maximize,
  infrastructure: Anchor,
  temporal: Calendar,
  connectivity: Globe,
};

const VIEW_BUTTONS: { id: ViewMode; icon: typeof Map; label: string; span2?: boolean }[] = [
  { id: "2d", icon: LayoutDashboard, label: "2D PCA" },
  { id: "3d", icon: Box, label: "3D PCA" },
  { id: "map", icon: Map, label: "Map" },
  { id: "corr", icon: Grid, label: "Correlation" },
  { id: "plots", icon: Image, label: "Plots", span2: true },
];

function assignGroups(
  members: DashboardPort[],
  allPorts: DashboardPort[],
  colorMode: ColorMode,
  pData: ProfileResult,
) {
  const groups: Record<string, { ports: DashboardPort[]; color: string }> = {};
  members.forEach((p) => {
    let gName = "";
    let gColor = "";
    if (colorMode === "dominant") {
      gName = p.dominant;
      gColor = p.color;
    } else {
      const origIdx = allPorts.indexOf(p);
      const cId = pData.clusters[origIdx];
      gName = shortGroupName(pData.cluster_names[cId] || `C${Number(cId) + 1}`);
      gColor = CLUSTER_PALETTE[cId % CLUSTER_PALETTE.length];
    }
    if (!groups[gName]) groups[gName] = { ports: [], color: gColor };
    groups[gName].ports.push(p);
  });
  return groups;
}

export function PortDashboardApp() {
  const { ports, pcaData, profiles, featureDocs } = data;

  const [currentProfile, setCurrentProfile] = useState("fleet_mix");
  const [currentView, setCurrentView] = useState<ViewMode>("map");
  const [colorMode, setColorModeState] = useState<ColorMode>("cluster");
  const [searchTerm, setSearchTerm] = useState("");
  const [showAnomaliesList, setShowAnomaliesList] = useState(false);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const chartRef = useRef<HTMLDivElement>(null);
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const plotlyRef = useRef<any>(null);

  const { tooltip, showTooltip, moveTooltip, hideTooltip } = useTooltip();

  const pData = pcaData[currentProfile];
  const profileDef = profiles[currentProfile];

  const totalVarDisplay = useMemo(() => {
    if (currentView === "corr") return "100";
    if (currentView === "map") return "N/A";
    return pData.variance_clustering_total.toFixed(1);
  }, [currentView, pData]);

  const noisePct = ((pData.dbscan_n_noise / ports.length) * 100).toFixed(1);
  const anomalies = pData.forced_assignments;
  const hasAnomalies = anomalies && anomalies.length > 0;
  const isCorrOrPlots = currentView === "corr" || currentView === "plots";

  const filteredPorts = useMemo(
    () =>
      ports.filter(
        (p) =>
          p.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
          p.id.toLowerCase().includes(searchTerm.toLowerCase()) ||
          p.country.toLowerCase().includes(searchTerm.toLowerCase()) ||
          p.dominant.toLowerCase().includes(searchTerm.toLowerCase()),
      ),
    [ports, searchTerm],
  );

  const groups = useMemo(
    () => assignGroups(filteredPorts, ports, colorMode, pData),
    [filteredPorts, ports, colorMode, pData],
  );

  const selectedCompare = useMemo(() => {
    if (!selectedId) return null;
    const port = ports.find((p) => p.id === selectedId);
    if (!port) return null;
    const allMeans = profileMeans(filteredPorts, profileDef.cols);
    const entry = Object.values(groups).find((g) => g.ports.some((x) => x.id === selectedId));
    const members = entry?.ports ?? [port];
    const groupName =
      Object.keys(groups).find((k) => groups[k].ports.some((x) => x.id === selectedId)) ||
      port.dominant;
    const compareToAll = members.length < 2;
    return comparePort(port, {
      profile: profileDef,
      groupName,
      groupSize: members.length,
      groupMeans: compareToAll ? allMeans : profileMeans(members, profileDef.cols),
      vsLabel: compareToAll ? "vs all ports" : "vs group mean",
    });
  }, [selectedId, ports, groups, filteredPorts, profileDef]);

  const setProfile = (p: string) => {
    setCurrentProfile(p);
    setShowAnomaliesList(false);
  };

  useEffect(() => {
    let cancelled = false;
    import("plotly.js-dist-min").then((mod) => {
      if (cancelled) return;
      plotlyRef.current = mod.default;
      draw();
    });
    return () => {
      cancelled = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    if (plotlyRef.current) draw();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentProfile, currentView, colorMode, searchTerm]);

  useEffect(() => {
    const onResize = () => {
      if (plotlyRef.current && chartRef.current) {
        plotlyRef.current.Plots.resize(chartRef.current);
      }
    };
    window.addEventListener("resize", onResize);
    return () => window.removeEventListener("resize", onResize);
  }, []);

  function draw() {
    if (!chartRef.current) return;
    const Plotly = plotlyRef.current;
    const config = { responsive: true, displayModeBar: true, scrollZoom: true, displaylogo: false };

    if (currentView === "corr") {
      const trace = {
        z: pData.corr.z,
        x: pData.corr.x,
        y: pData.corr.y,
        type: "heatmap",
        colorscale: [
          [0, "#ef4444"],
          [0.5, "#ffffff"],
          [1, "#3b82f6"],
        ],
        zmin: -1,
        zmax: 1,
        hovertemplate:
          "X: %{x}<br>Y: %{y}<br>Corr: <b>%{z}</b><extra></extra>",
        hoverlabel: {
          bgcolor: "#ffffff",
          bordercolor: "#e2e8f0",
          font: { family: UI_FONT, size: 12, color: "#0f172a" },
          align: "left",
        },
      };
      const layout = {
        font: { family: UI_FONT, color: "#334155" },
        margin: { l: 120, r: 20, t: 24, b: 120 },
        paper_bgcolor: "white",
        plot_bgcolor: "white",
        hoverlabel: {
          bgcolor: "#ffffff",
          bordercolor: "#e2e8f0",
          font: { family: UI_FONT, size: 12, color: "#0f172a" },
          align: "left",
        },
      };
      Plotly.react(chartRef.current, [trace], layout, {
        ...config,
        displaylogo: false,
      });
      return;
    }

    const maxVisits = Math.max(...ports.map((p) => p.visits));
    const groupKeys = Object.keys(groups).sort();
    const allMeans = profileMeans(filteredPorts, profileDef.cols);

    const hoverlabel = {
      bgcolor: "#ffffff",
      bordercolor: "#e2e8f0",
      font: { family: UI_FONT, size: 12, color: "#0f172a" },
      align: "left",
    };

    const traces = groupKeys.map((t) => {
      const tPorts = groups[t].ports;
      const tColor = groups[t].color;
      const indices = tPorts.map((p) => ports.indexOf(p));
      const isMap = currentView === "map";
      const compareToAll = tPorts.length < 2;
      const means = compareToAll ? allMeans : profileMeans(tPorts, profileDef.cols);
      const vsLabel = compareToAll ? "vs all ports" : "vs group mean";
      const hoverText = tPorts.map((p) =>
        compareHoverText(
          comparePort(p, {
            profile: profileDef,
            groupName: t,
            groupSize: tPorts.length,
            groupMeans: means,
            vsLabel,
          }),
        ),
      );

      const base: Record<string, unknown> = {
        name: shortGroupName(t),
        text: hoverText,
        customdata: tPorts.map((p) => p.id),
        mode: "markers",
        hoverinfo: "text",
        hovertemplate: null,
        marker: {
          size: tPorts.map((p) => Math.sqrt(p.visits / maxVisits) * (isMap ? 25 : 40) + (isMap ? 4 : 5)),
          color: tColor,
          opacity: 0.75,
          line: { width: 0.5, color: "#fff" },
        },
        hoverlabel,
      };

      if (isMap) {
        base.type = "scattermapbox";
        base.lat = tPorts.map((p) => p.lat);
        base.lon = tPorts.map((p) => p.lon);
      } else if (currentView === "3d") {
        base.type = "scatter3d";
        base.x = indices.map((i) => pData.coords[i][0]);
        base.y = indices.map((i) => pData.coords[i][1]);
        base.z = indices.map((i) => pData.coords[i][2]);
      } else {
        base.type = "scatter";
        base.x = indices.map((i) => pData.coords[i][0]);
        base.y = indices.map((i) => pData.coords[i][1]);
      }
      return base;
    });

    const chartDiv = chartRef.current;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const persisted = (chartDiv as any)?.layout;
    const currentMapbox: Record<string, unknown> = {
      style: "white-bg",
      layers: [
        {
          sourcetype: "raster",
          source: [
            "https://tile.openstreetmap.org/{z}/{x}/{y}.png",
          ],
          below: "traces",
        },
      ],
      center: { lat: 55, lon: 18 },
      zoom: 4,
    };
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let currentScene: any = {
      xaxis: { title: "PC1", backgroundcolor: "#ffffff", gridcolor: "#e2e8f0" },
      yaxis: { title: "PC2", backgroundcolor: "#ffffff", gridcolor: "#e2e8f0" },
      zaxis: { title: "PC3", backgroundcolor: "#ffffff", gridcolor: "#e2e8f0" },
      aspectmode: "cube",
    };

    if (persisted) {
      if (persisted.mapbox) {
        currentMapbox.center = persisted.mapbox.center || currentMapbox.center;
        currentMapbox.zoom = persisted.mapbox.zoom || currentMapbox.zoom;
      }
      if (persisted.scene && persisted.scene.camera) {
        currentScene.camera = persisted.scene.camera;
      }
    }

    const isMap = currentView === "map";
    const layout = {
      font: { family: UI_FONT, color: "#334155" },
      margin: isMap
        ? { l: 0, r: 0, t: 0, b: 0 }
        : {
            l: currentView === "3d" ? 0 : 48,
            r: currentView === "3d" ? 0 : 16,
            t: currentView === "3d" ? 40 : 56,
            b: currentView === "2d" ? 72 : currentView === "3d" ? 0 : 16,
          },
      hovermode: "closest",
      paper_bgcolor: "white",
      plot_bgcolor: "white",
      hoverlabel: {
        bgcolor: "#ffffff",
        bordercolor: "#e2e8f0",
        align: "left",
        font: { family: UI_FONT, size: 12, color: "#0f172a" },
      },
      title: isMap || currentView === "3d"
        ? { text: "" }
        : {
            text: profileDef.label,
            font: { family: UI_FONT, size: 14, weight: 600 },
            x: 0.05,
            y: 0.97,
          },
      legend: isMap
        ? {
            orientation: "v",
            x: 0.01,
            y: 0.02,
            xanchor: "left",
            yanchor: "bottom",
            bgcolor: "rgba(255,255,255,0.94)",
            bordercolor: "#e2e8f0",
            borderwidth: 1,
            font: { size: 11, family: UI_FONT },
            itemsizing: "constant",
          }
        : {
            orientation: "h",
            y: currentView === "2d" ? -0.12 : 0,
            x: 0.5,
            xanchor: "center",
          },
      xaxis: {
        title: "PC1 (" + pData.variance[0] + "%)",
        gridcolor: "#f1f5f9",
        zeroline: false,
      },
      yaxis: {
        title: "PC2 (" + pData.variance[1] + "%)",
        gridcolor: "#f1f5f9",
        zeroline: false,
      },
      scene: currentScene,
      mapbox: currentMapbox,
    };

    const viewConfig = {
      ...config,
      displayModeBar: !isMap,
      displaylogo: false,
    };

    void Plotly.react(chartDiv, traces, layout, viewConfig).then(() => {
      if (chartRef.current) Plotly.Plots.resize(chartRef.current);
      const gd = chartRef.current as
        | { on?: (ev: string, fn: (e: { points?: Array<{ customdata?: unknown }> }) => void) => void; removeAllListeners?: (ev: string) => void }
        | null;
      if (!gd?.on) return;
      gd.removeAllListeners?.("plotly_click");
      gd.on("plotly_click", (ev) => {
        const id = ev.points?.[0]?.customdata;
        if (typeof id === "string" && id) setSelectedId(id);
      });
    });
  }

  return (
    <>
      {tooltip && (
        <div
          className="global-tooltip visible"
          style={{ left: tooltip.x + "px", top: tooltip.y + "px" }}
          dangerouslySetInnerHTML={{ __html: tooltip.text }}
        />
      )}
      <div className="main-container">
        <Sidebar>
          <SidebarHeader title="Port Profiles" />
          <SidebarBody>
            <div className="control-section">
              <SectionTitle>Profile</SectionTitle>
              <ButtonGrid columns={2}>
                {Object.entries(profiles).map(([key, def]) => {
                  const Icon = PROFILE_ICONS[key] ?? Ship;
                  return (
                    <ToggleButton
                      key={key}
                      pressed={key === currentProfile}
                      onClick={() => setProfile(key)}
                    >
                      <Icon aria-hidden="true" /> {def.label}
                    </ToggleButton>
                  );
                })}
              </ButtonGrid>
            </div>

            <div className="control-section">
              <SectionTitle>View</SectionTitle>
              <ButtonGrid columns={2}>
                {VIEW_BUTTONS.map(({ id, icon: Icon, label, span2 }) => (
                  <ToggleButton
                    key={id}
                    pressed={id === currentView}
                    span={span2 ? 2 : undefined}
                    onClick={() => setCurrentView(id)}
                  >
                    <Icon aria-hidden="true" /> {label}
                  </ToggleButton>
                ))}
              </ButtonGrid>
            </div>

            <div className="control-section">
              <SectionTitle>Color</SectionTitle>
              <ButtonGrid columns={2}>
                <ToggleButton
                  id="c_dominant"
                  pressed={colorMode === "dominant"}
                  disabled={isCorrOrPlots}
                  onClick={() => setColorModeState("dominant")}
                >
                  <Tag aria-hidden="true" /> Dominant
                </ToggleButton>
                <ToggleButton
                  id="c_cluster"
                  pressed={colorMode === "cluster"}
                  disabled={isCorrOrPlots}
                  onClick={() => setColorModeState("cluster")}
                >
                  <PieChart aria-hidden="true" /> Cluster
                </ToggleButton>
              </ButtonGrid>
            </div>

            <PortComparePanel compare={selectedCompare} onClear={() => setSelectedId(null)} />

            <ClusterMetrics
              pData={pData}
              noisePct={noisePct}
              showAnomaliesList={showAnomaliesList}
              hasAnomalies={!!hasAnomalies}
              onToggleAnomalies={() => {
                if (!hasAnomalies) return;
                setShowAnomaliesList(!showAnomaliesList);
              }}
              showTooltip={showTooltip}
              moveTooltip={moveTooltip}
              hideTooltip={hideTooltip}
            />

            {hasAnomalies && showAnomaliesList && (
              <div className="anomaly-panel">
                <h3>
                  <AlertTriangle size={12} aria-hidden="true" /> DBSCAN noise
                </h3>
                <p>Assigned to a cluster by k-means after DBSCAN flagged them as noise.</p>
                <div className="anomaly-list">
                  {anomalies.map((a, i) => {
                    const clusterName = pData.cluster_names[String(a.kmeans)];
                    const cleanClusterName = clusterName
                      ? shortGroupName(clusterName)
                      : `C${a.kmeans + 1}`;
                    return (
                      <div key={i} className="anomaly-row">
                        <span>{a.port}</span>
                        <span>{cleanClusterName}</span>
                      </div>
                    );
                  })}
                </div>
              </div>
            )}

            {!isCorrOrPlots && (
              <div className="control-section">
                <SectionTitle>Search</SectionTitle>
                <SearchField
                  id="portSearch"
                  label="Search port"
                  placeholder="Port, locode, country…"
                  value={searchTerm}
                  onChange={setSearchTerm}
                />
              </div>
            )}
            <div className="control-section">
              <SectionTitle>Active features</SectionTitle>
              <div className="feat-tiles">
                {profileDef.cols.map((c) => {
                  const doc = featureDocs[c] || "Detailed documentation unavailable.";
                  return (
                    <div
                      key={c}
                      className="feat-tile"
                      onMouseEnter={(e) => showTooltip(e, doc)}
                      onMouseLeave={hideTooltip}
                      onMouseMove={(e: MouseEvent) => moveTooltip(e)}
                    >
                      {featureLabel(c)}
                    </div>
                  );
                })}
              </div>
            </div>
          </SidebarBody>
          {(currentView === "2d" || currentView === "3d") && (
            <StatRow columns={1}>
              <StatCard value={`${totalVarDisplay}%`} label="Variance" />
            </StatRow>
          )}
        </Sidebar>
        <div className={"content" + (currentView === "map" ? " content--map" : "")}>
          <div className="chart-card">
            <div
              id="chart"
              ref={chartRef}
              style={{ display: currentView === "plots" ? "none" : "block" }}
            />
            {currentView === "plots" && (
              <PlotsGrid profile={currentProfile} basePath={PLOTS_BASE_PATH} />
            )}
          </div>
          {currentView === "map" && (
            <p className="map-attrib">
              ©{" "}
              <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>
            </p>
          )}
        </div>
      </div>
    </>
  );
}
